--This table loads the cleaned electric vehicle data from the source into the database
CREATE TABLE EV_ADOPTION (
    state VARCHAR2(50),
    year NUMBER,
    ev_registrations NUMBER,
    total_vehicles NUMBER,
    ev_share_percent FLOAT,
    stations NUMBER,
    total_charging_outlets NUMBER,
    level_1 NUMBER,
    level_2 NUMBER,
    dc_fast NUMBER,
    fuel_economy FLOAT,
    incentives NUMBER,
    population_20_64 NUMBER,
    education_bachelor NUMBER,
    labour_force_participation_rate FLOAT,
    unemployment_rate FLOAT,
    bachelor_attainment FLOAT,
    per_cap_income NUMBER,
    affectweather FLOAT,
    devharm FLOAT,
    discuss FLOAT,
    exp FLOAT,
    localofficials FLOAT,
    personal FLOAT,
    reducetax FLOAT,
    regulate FLOAT,
    worried FLOAT,
    price_cents_per_kwh FLOAT,
    gasoline_price_per_gallon FLOAT,
    trucks NUMBER,
    trucks_share FLOAT,
    party VARCHAR2(20)
);
